package qmlgrid

// This file is automatically generated by gopkg.in/qml.v1/cmd/genqrc

import (
	"io/ioutil"
	"os"
	"path/filepath"

	"gopkg.in/qml.v1"
)

func init() {
	var r *qml.Resources
	var err error
	if os.Getenv("QRC_REPACK") == "1" {
		err = qrcRepackResources()
		if err != nil {
			panic("cannot repack qrc resources: " + err.Error())
		}
		r, err = qml.ParseResources(qrcResourcesRepacked)
	} else {
		r, err = qml.ParseResourcesString(qrcResourcesData)
	}
	if err != nil {
		panic("cannot parse bundled resources data: " + err.Error())
	}
	qml.LoadResources(r)
}

func qrcRepackResources() error {
	subdirs := []string{"grid.qml", "tile.qml"}
	var rp qml.ResourcesPacker
	for _, subdir := range subdirs {
		err := filepath.Walk(subdir, func(path string, info os.FileInfo, err error) error {
			if err != nil {
				return err
			}
			if info.IsDir() {
				return nil
			}
			data, err := ioutil.ReadFile(path)
			if err != nil {
				return err
			}
			rp.Add(filepath.ToSlash(path), data)
			return nil
		})
		if err != nil {
			return err
		}
	}
	qrcResourcesRepacked = rp.Pack().Bytes()
	return nil
}

var qrcResourcesRepacked []byte
var qrcResourcesData = "qres\x00\x00\x00\x01\x00\x00\x04\xb1\x00\x00\x00\x14\x00\x00\x04\x85\x00\x00\x03{import QtQuick 2.0\n\nRectangle {\n    id: tile\n    property int kind: 0\n\n    border { width: 1; color: \"#FFFFFF\" }\n\n    state: \"DEFAULT\"\n    states: [\n        State {\n            name: \"DEFAULT\"\n            when: kind == 0\n            PropertyChanges { target: tile; color: \"#ecf0f1\" }\n        },\n\n        State {\n            name: \"BLOCKED\"\n            when: kind == 1\n            PropertyChanges { target: tile; color: \"#2c3e50\" }\n        },\n\n        State {\n            name: \"VISITED\"\n            when: kind == 2\n            PropertyChanges { target: tile; color: \"#7f8c8d\" }\n        },\n\n        State {\n            name: \"ACTIVE\"\n            when: kind == 3\n            PropertyChanges { target: tile; color: \"#27ae60\" }\n        },\n\n        State {\n            name: \"EXTREMITY\"\n            when: kind == 4\n            PropertyChanges { target: tile; color: \"#e74c3c\" }\n        }\n    ]\n}\n\x00\x00\x00\xeeimport QtQuick 2.0\n\nRectangle {\n    id: root\n    color: \"#e5e5e5\"\n\n    Component.onCompleted: grid.draw(canvas)\n\n    Item {\n        id: canvas\n        width: parent.width\n        anchors { top: parent.top; bottom: parent.bottom }\n    }\n}\n\x00\b\x00([\\\x00t\x00i\x00l\x00e\x00.\x00q\x00m\x00l\x00\b\b\xf7]\xfc\x00g\x00r\x00i\x00d\x00.\x00q\x00m\x00l\x00\x00\x00\x00\x00\x02\x00\x00\x00\x02\x00\x00\x00\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x01\x00\x00\x00\x00\x00\x00\x00\x16\x00\x00\x00\x00\x00\x01\x00\x00\x03\u007f"
